name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pytest
  - pip:
      - azure-identity
      - azure-storage-blob
      - azure-cli
