# L.I.F.E Platform - Conda Environment Configuration
# Azure Marketplace Ready - Enterprise Neural Processing System
# Copyright 2025 - Sergio Paya Borrull

name: life-ci

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  - pytest>=7.4.0
  - flake8>=6.0.0
  
  # Additional pip packages
  - pip:
    - azure-identity>=1.14.0
    - azure-storage-blob>=12.17.0
    - azure-monitor-query>=1.1.0
    - azure-keyvault-secrets>=4.7.0
    - azure-servicebus>=7.11.0
    - azure-functions>=1.15.0
    - azure-cli>=2.50.0
    - tensorflow>=2.13.0
    - torch>=2.0.0
    - mne>=1.4.0
    - nilearn>=0.10.0
    - joblib>=1.3.0
    - fastapi>=0.100.0
    - uvicorn>=0.23.0
    - pydantic>=2.0.0
    - pytest-asyncio>=0.21.0
    - pytest-cov>=4.1.0
