# L.I.F.E Platform - Conda Environment Configuration
# Copyright 2025 - Sergio Paya Borrull
# Azure Marketplace Offer ID: 9a600d96-fe1e-420b-902a-a0c42c561adb

name: life-ci

channels:
  - defaults
  - conda-forge

dependencies:
  # Core Python
  - python=3.11
  - pip
  
  # Scientific Computing
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  
  # Testing
  - pytest>=7.4.0
  - pytest-asyncio>=0.21.0
  - pytest-cov>=4.1.0
  
  # Development
  - flake8>=6.0.0
  
  # Additional dependencies via pip
  - pip:
    # Azure SDK Components
    - azure-identity>=1.14.0
    - azure-storage-blob>=12.17.0
    - azure-monitor-query>=1.1.0
    - azure-keyvault-secrets>=4.7.0
    - azure-servicebus>=7.11.0
    - azure-functions>=1.15.0
    
    # Neural Processing (lighter versions for CI)
    - mne>=1.4.0
    - joblib>=1.3.0
    
    # API Framework
    - fastapi>=0.100.0
    - uvicorn>=0.23.0
    - pydantic>=2.0.0
    
    # Monitoring
    - structlog>=23.1.0
    
    # Security
    - cryptography>=41.0.0
    - pyjwt>=2.8.0
    
    # Configuration
    - python-dotenv>=1.0.0
    - pyyaml>=6.0
