# Here is the updated workflow file content with the new condition.

# Sample workflow example
name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Running script"
        if: github.sha != '1b3d092f142c8428adc5a6d48dd0f4fc1cb0d2a4'